log_dir: 'logs'
device_name: 'cuda'  # cuda, cpu
seed: 42
dataset:
  name: 'spoofing_combined_2023'
  root: '~/datasets/spoofing_combined_2023'
  resize_size: 232
  crop_size: 224
  train_set: 'train_uniform.csv'
  val_set: 'val_uniform.csv'

model:
  base: 'efficientformerv2_s1'
  pretrained: True  # Attempt to load ImageNet pretrained weights
  checkpoint_path: ""
  resume: False
  resume_strict: True
  dropout: 0.1
  descriptor_size: 256  # Where applicable

train:
  batch_size: 16
  optimizer: 'adamw'
  lr: 0.002
  weight_decay: 1e-5
  num_epochs: 300
  scheduler_name: cosr
  restart_epoch: 10  # for CosineAnnealingWarmRestarts
  restart_multiplier: 2  # for CosineAnnealingWarmRestarts
  load_optimizer: False
  load_scheduler: False

val:
  batch_size: 16
